<?php
	$galleta=array(
	"Si fueras una galleta serias una Galleta de Gota",
	"Si fueras una galleta serias una Galleta Prensada",
	"Si fueras una galleta serias una Galleta Moldeada",
	"Si fueras una galleta serias una Galleta de gota",
	"Si fueras una galleta serias una Galleta Enrollada",
	"Si fueras una galleta serias una Galleta de Nevera",
	"Si fueras una galleta serias una Galleta de Barra",
	"Si fueras una galleta serias una Galleta de Sin Hornear",
	"Si fueras una galleta serias una Galleta con Chispas de Chocolate",
	"Si fueras una galleta serias una Galleta de Avena con Pasas",
	"Si fueras una galleta serias una Galleta de Mantequilla de Mani",
	"Si fueras una galleta serias una Galleta de Azucar",
	"Si fueras una galleta serias una Galleta en Blanco y Negro",
	"Si fueras una galleta serias una Snickerdoodles",
	"Si fueras una galleta serias una Galleta de Terciopelo Rojo",
	"Si fueras una galleta serias una Galleta Arrugada",
	"Si fueras una galleta serias una Whoopie Pies",
	"Si fueras una galleta serias una Galleta de Melaza",	
	"Si fueras una galleta serias una Oreo",	
	"Si fueras una galleta serias una Galleta de la Fortuna",
	"Si fueras una galleta serias una Galleta de Animales",
	"Si fueras una galleta serias un Alfajor",
	"Si fueras una galleta serias una Galleta de Mantequilla(Dinamarca)",
	"Si fueras una galleta serias una Galleta de Mantequilla(Escocia)",
	"Si fueras una galleta serias una Galleta de Jengibre(Inglaterra)",
	"Si fueras una galleta serias una Galleta de Jengibre(Alemania)",
	"Si fueras una galleta serias una Galleta de Media luna de Vainilla(Austria)",
	"Si fueras una galleta serias un Macaron Frances",
	"Si fueras una galleta serias una Galleta de Merengue",
	"Si fueras una galleta serias una Galleta Speculoos",
	"Si fueras una galleta serias un KrumKake",
	"Si fueras una galleta serias un Stroopwafel",
	"Si fueras una galleta serias unos Macarrones(Italia)",
	"Si fueras una galleta serias una Galleta de gota",
	"Si fueras una galleta serias una Savoiardi",
	"Si fueras una galleta serias una Galleta Amaretti di Saronno",
	"Si fueras una galleta serias una Kourabiedis",
	"Si fueras una galleta serias una Lengua de Gato",
	"Si fueras una galleta serias una Galleta de Singapur",
	"Si fueras una galleta serias una Galleta de Matcha",
	"Si fueras una galleta serias una Galleta de Sakura",
	"Si fueras una galleta serias una Acibadem Kurabiyesi",
	"Si fueras una galleta serias una Ghoriba Bahla",
	"Si fueras una galleta serias una Kaab el Ghazal",
	"Si fueras una galleta serias una Kaak al-Eid",
	"Si fueras una galleta serias una Ghorayeba",
	"Si fueras una galleta serias una Galleta Anzac");
	$random=array_rand($galleta);
	echo $galleta[$random]
?>